### ISSUE TITLE
[Mobile app] Unable to install a mobile app (.apk)

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1090]
Pre-Conditions:
- IoTS should be up and running
- There should be a device enrolled as BYOD

1. Login to publisher and upload a mobile app as described at [1]
2. Install the app in an enrolled device either using a scheduled time or by selecting a role in en-install option as described at [2]
3. Check the relevant mobile device if the app is installed

Expected Results:-
- Mobile app should be installed

Actual Results:-
- Mobile app is not getting installed in relevant device/devices

[1] https://docs.wso2.com/display/IoTS300/Creating+an+Android+Application
[2] https://docs.wso2.com/display/IoTS300/Installing+and+Updating+Mobile+Apps

**Comment by pubudup** [comment]
@chamaraanu : Labels - Blocker, 3.1.0-alpha

**Comment by inoshperera** [comment]
Fixed with following commits,
https://github.com/wso2/cdmf-agent-android/commit/1760fdd8567635b083484c9d2f42779f0dd6333a
https://github.com/wso2/carbon-appmgt/pull/657

**Comment by pubudup** [comment]
@inoshperera : Seems like the issue still exists (Tested in Windows 2012 R2). Please check and update the ticket accordingly as discussed offline. Thanks!

**Comment by inoshperera** [comment]
Fixed with - https://github.com/wso2/cdmf-agent-android/pull/62

**Comment by pubudup** [comment]
@geethkokila , @madhawap : label - 3.1.0-beta

**Comment by pubudup** [comment]
Related issue created. #1194
