### ISSUE TITLE
Geo dashboard UI improvements

### ISSUE THREAD

**Issue by sherenem** [wso2/product-iots#1096]
1. After clicking Add Geo Fence Exit Alert and Add Geo Fence Enter Alert, the **Draw Area** and **Enter Area** buttons are a bit too high  on the screen when there are no existing fences and it almost overlaps the table above it. See attachment. Would be good if we can add a little spacing in between please. The stationary alert screen has a good spacing. 

**Geo Fence Exit/Enter Alert**
![image](https://user-images.githubusercontent.com/17191212/27733012-9f3c3d3a-5db1-11e7-9788-cb148a071fe4.png)

**Stationary Alert**
![image](https://user-images.githubusercontent.com/17191212/27733032-b75710ca-5db1-11e7-91a3-e4873563220a.png)

2. After drawing a fence, the UI to enter a fence name has the following help tip "Name of the selected area(i.e colombo)" below the Fence Name text box. Since i.e. is short for "that is", shall we have this "e.g.," instead of "i.e." so that it reads "Name of the selected area(**e.g.**, colombo)" ? 

![image](https://user-images.githubusercontent.com/17191212/27733071-d09f8d1e-5db1-11e7-8a75-ea0f077b20b6.png)

3. After drawing a geo area for the stationary alert, the fence name text box has "stationary" spelled as "stationery". "Stationery" with an e is used only to refer to stuff like pens, papers, rulers etc. Replace the 'e' with an 'a'. 

![image](https://user-images.githubusercontent.com/17191212/27733090-e1a968dc-5db1-11e7-8ffa-921aecf00242.png)

**Comment by rasika** [comment]
The first issue is fixed with hiding the table when the alerts are not available.
<img width="1018" alt="screen shot 2017-07-05 at 10 42 28 am" src="https://user-images.githubusercontent.com/1448489/27849957-b66faf44-616e-11e7-941a-0dfae03a2707.png">

**Comment by shavidissa** [comment]
Hi Rasika,

I am reopening this as a few issues still seem to persist.

- Geofencing should be one word. Can we change all the places, please?
- Oh snap! Can't find any geo-fence areas,please draw a new area or try again.  - We need a space between the , and please -  "areas, please".
