### ISSUE TITLE
AGENT_LOG:: Connection to MQTT Broker at: tcp://localhost:1886 failed

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#523]
[INFO] TransportUtils - The IP String - 'XMPP:' is invalid. It needs to be in format '`<PROTOCOL>://<HOST>:<PORT>`'. 

 [ERROR] AgentManager - XMPP Endpoint String - XMPP:, provided in the configuration file is invalid. 

 [INFO] MQTTTransportHandler - MQTT subscriber was created with ClientID : admin:1h7tr8keob3hh 

 AGENT_LOG:: Connection to MQTT Broker at: tcp://localhost:1886 failed. <p>Reference: <a href='https://wso2.org/jira/browse/IOTS-529'>https://wso2.org/jira/browse/IOTS-529</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing

**Comment by wiwengweng** [comment]
hi, geethkokila. I still get this issue in iot-server-3.3.0. How can I avoid this?
I have use the change-ip script to change 'localhost' to my IP.  And the virtual fire alarm sample throw this error:

````
12:30:05 [WARN] FireAlarmMQTTCommunicator - AGENT_LOG:: Connection to MQTT Broker at: tcp://10.1.74.52:1886 failed.
 Will retry in 5000 milli-seconds.
12:30:05 [INFO] AgentUtilOperations - AGENT_LOG:: Request to refresh OAuth token was sent to [http://10.1.74.52:8280/token] with payload [grant_type=refresh_token&refresh_token=a9f9b7bf-7e62-384c-9934-486cb773e2e0&scope=device_type_virtual_firealarm device_vbbtjqlmqb75].
12:30:05 [INFO] AgentUtilOperations - AGENT_LOG:: Response [401:Unauthorized] was received for token refresh attempt.
12:30:05 [WARN] AgentUtilOperations - AGENT_LOG:: There was an issue with refreshing the Access Token.
````

Then I disable broker authentication and authorization following this [link](https://docs.wso2.com/display/IOTS330/FAQ#FAQ-HowcanIdisableauthenticationforMQTTclients?)

but still not working. Can you help with this? Thanks.

Andes
