### ISSUE TITLE
[IOTS-437] IOTS /devicemgt web page is showing "Error 500"

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#628]
An Error Occurred! HTTP Status : 500 {/app/modules/oauth/token-handlers.js}  Could not set up encoded tenant based client credentials to session context as the server is unable to obtain such credentials - setUpEncodedTenantBasedClientAppCredentials<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-437'>https://wso2.org/jira/browse/IOTS-437</a></p>

**Comment by geethkokila** [comment]
This is fixed and tested. Hence closing

**Comment by jameswangz** [comment]
Hi, which version is this issue fixed?  I'm using the latest zip version which was downloaded from the official website and still getting this error.

**Comment by jiangcluster** [comment]
i  [Configuring WSO2 IoT Server with the IP or Hostname](https://docs.wso2.com/display/IoTS300/Configuring+WSO2+IoT+Server+with+the+IP+or+Hostname) but 
i still getting this error too with V3.0.0
