### ISSUE TITLE
[IOTS-426] Getting exception "From property does not contains all the required values for event adapter type oauth-mqtt"

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#631]
When creating an event receiver, if oauth-mqtt is selected as Input Event Adapter Type it doesn't show a field to enter the 'topic' under Adapter Properties.  Also after clicking the event "Add event adapter" get 'Failed to add event receiver, Exception: From property does not contains all the required values for event adapter type oauth-mqtt' exception.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-426'>https://wso2.org/jira/browse/IOTS-426</a></p>

**Comment by geethkokila** [comment]
This is fixed and tested. Hence closing the issue.

**Comment by jiangcluster** [comment]
which version fixed this bug? i use RC4,still get this error
